kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "hello-world-ingress.fullname" . }}
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service }}
                port:
                  number: 8080